# command line: main.py --config config/wlasl1000/default.yaml

base_lr: 0.05
batch_size: 16
config: config/wlasl1000/default.yaml
device:
- 0
eval_interval: 1
feeder: feeders.feeder_wlasl.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.ctrgcn.Model
model_args:
  graph: graph.mediapipe75.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 1000
  num_person: 1
  num_point: 75
model_saved_name: ''
nesterov: false
num_epoch: 30
num_worker: 2
optimizer: SGD
phase: train
print_log: true
save_epoch: 1
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
test_batch_size: 16
test_feeder_args:
  data_path: data/wlasl_data.npy
  debug: false
  label_path: data/wlasl_label.pkl
  split: test
  window_size: 32
train_feeder_args:
  data_path: data/wlasl_data.npy
  debug: false
  label_path: data/wlasl_label.pkl
  split: train
  window_size: 32
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: ./work_dir/wlasl1000/ctrgcn
